name: NPM CI
on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [14, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
  tag_version:
    runs-on: ubuntu-latest
    needs: test
    if: |
      (github.repository_owner == 'StrangeSkies') &&
      (needs.test.result == 'success') &&
      (github.event_name == 'push') &&
      (github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DRONE_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: |
          package_version=$(npm -s run env echo '$npm_package_version')
          if [ ! $(git tag -l v$package_version) ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git tag -a v$package_version -m "release version: $package_version date: $(date)"
            git push origin v$package_version
          fi
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: |
      (github.repository_owner == 'StrangeSkies') &&
      (needs.test.result == 'success') &&
      (github.event_name == 'push') &&
      startsWith(github.ref, 'refs/tags')
    environment:
      name: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
